# Learn more about this config here: https://pre-commit.com/

# To enable these pre-commit hooks run: `uv tool install pre-commit`
# or `pipx install pre-commit` or `brew install pre-commit`, etc.
# Then in the project root directory run `pre-commit install`

repos:
  #- repo: https://github.com/pre-commit/pre-commit-hooks
  #  rev: v6.0.0
  #  hooks:
  #    - id: check-added-large-files
  #    - id: check-ast
  #    - id: check-builtin-literals
  #    - id: check-case-conflict
  #    - id: check-docstring-first
  #    - id: check-executables-have-shebangs
  #    - id: check-json
  #    - id: check-merge-conflict
  #    - id: check-shebang-scripts-are-executable
  #    - id: check-symlinks
  #    - id: check-toml
  #    - id: check-vcs-permalinks
  #    - id: check-xml
  #    - id: check-yaml
  #    - id: debug-statements
  #    - id: destroyed-symlinks
  #    - id: detect-private-key
  #    - id: end-of-file-fixer
  #    - id: file-contents-sorter
  #    - id: fix-byte-order-marker
  #    - id: forbid-new-submodules
  #    - id: forbid-submodules
  #    - id: mixed-line-ending
  #      args:
  #        - --fix=lf
  #    - id: requirements-txt-fixer
  #    - id: sort-simple-yaml
  #    - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell # See pyproject.toml for args
        additional_dependencies:
          - tomli

  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v1.17.1
  #  hooks:
  #  -   id: mypy

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
    #  - id: ruff-format
