site_name: HTTPX
site_description: A next-generation HTTP client for Python.

theme:
    name: 'material'

repo_name: encode/httpx
repo_url: https://www.python-httpx.org/
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - QuickStart: 'quickstart.md'
    - Advanced Usage: 'advanced.md'
    - HTTP/2 Support: 'http2.md'
    - Environment Variables: 'environment_variables.md'
    - Requests Compatibility: 'compatibility.md'
    - Developer Interface: 'api.md'
    - Contributing: 'contributing.md'

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc

extra_css:
    - css/custom.css
