site_name: HTTPX
site_description: A next-generation HTTP client for Python.

theme:
    name: 'material'

repo_name: encode/httpx
repo_url: https://github.com/encode/httpx
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - QuickStart: 'quickstart.md'
    - Advanced Usage: 'advanced.md'
    - Environment Variables: 'environment_variables.md'
    - Parallel Requests: 'parallel.md'
    - Async Client: 'async.md'
    - Requests Compatibility: 'compatibility.md'
    - Developer Interface: 'api.md'
    - Contributing: 'contributing.md'

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc

extra_css:
    - css/custom.css
