site_name: HTTP3
site_description: The next generation HTTP client.

theme:
    name: 'material'

repo_name: encode/http3
repo_url: https://github.com/encode/http3
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - QuickStart: 'quickstart.md'
    - Parallel Requests: 'parallel.md'
    - Async Client: 'async.md'
    - Requests Compatibility: 'compatibility.md'
    - Developer Interface: 'api.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
